


export const SEARCH_REQUEST="SEARCH_REQUEST"
export const SEARCH_SUCCESS="SEARCH_SUCCESS"
export const SEARCH_FAILURE="SEARCH_FAILURE"


export const ADD_COMPANY_REQUEST="ADD_COMPANY_REQUEST"
export const ADD_COMPANY_SUCCESS="ADD_COMPANY_SUCCESS"
export const ADD_COMPANY_FAILURE="ADD_COMPANY_FAILURE"


export const ADD_AD_REQUEST="ADD_AD_REQUEST"
export const ADD_AD_SUCCESS="ADD_AD_SUCCESS"
export const ADD_AD_FAILURE="ADD_AD_FAILURE"



export const GET_ALL_COMPANY_REQUEST="GET_ALL_COMPANY_REQUEST"
export const GET_ALL_COMPANY_SUCCESS="GET_ALL_COMPANY_SUCCESS"
export const GET_ALL_COMPANY_FAILURE="GET_ALL_COMPANY_FAILURE"